### ISSUE TITLE
La carte des biens de certains département ne s'affiche pas

### ISSUE THREAD

**Issue by JorisPLA7** [Webanimus/geomservices#1]

**Comment by AezardSR** [comment]
Le problème est sur plusieurs pages :
https://www.geomalert.webanimus.com/map/95/
https://www.geomalert.webanimus.com/map/06/
https://www.geomalert.webanimus.com/map/13/
https://www.geomalert.webanimus.com/map/14/
https://www.geomalert.webanimus.com/map/31/
https://www.geomalert.webanimus.com/map/33/
https://www.geomalert.webanimus.com/map/34/
https://www.geomalert.webanimus.com/map/36/
https://www.geomalert.webanimus.com/map/38/
https://www.geomalert.webanimus.com/map/44/
https://www.geomalert.webanimus.com/map/49/
https://www.geomalert.webanimus.com/map/51/
https://www.geomalert.webanimus.com/map/54/
https://www.geomalert.webanimus.com/map/59/
https://www.geomalert.webanimus.com/map/62/
https://www.geomalert.webanimus.com/map/67/
https://www.geomalert.webanimus.com/map/69/
https://www.geomalert.webanimus.com/map/74/
https://www.geomalert.webanimus.com/map/75/
https://www.geomalert.webanimus.com/map/76/
https://www.geomalert.webanimus.com/map/78/
https://www.geomalert.webanimus.com/map/83/
https://www.geomalert.webanimus.com/map/91/
https://www.geomalert.webanimus.com/map/92/
https://www.geomalert.webanimus.com/map/93/
https://www.geomalert.webanimus.com/map/94/
https://www.geomalert.webanimus.com/map/95/

**Comment by MercierCorentin** [comment]
Chelou, en prod, la fin de la balise n'est pas reconnue: 

![Image](https://github.com/Webanimus/geomservices/assets/46066895/eba42bca-200b-4037-99ec-f3bc8e618231)

**Comment by MercierCorentin** [comment]
Du coup on voit que c'est tronqué à `-0.147`

**Comment by MercierCorentin** [comment]
C'est bon on dirait, la prod était pas à jour, je comprend pas bien pk :/

**Comment by JorisPLA7** [comment]
👏👏👏
