### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by JorisPLA7** [Webanimus/geomservices#10]
Ajouter google analytics à ce site.

**Comment by MercierCorentin** [comment]
C'est déjà fait depuis un petit moment
<img width="1080" alt="Screenshot 2023-08-23 at 15 12 02" src="https://github.com/Webanimus/geomservices/assets/46066895/2b80c14b-8010-4d20-ae89-82daa9fbb2b9">

**Comment by MercierCorentin** [comment]
Fait et partagé avec ton gmail pro
