### ISSUE TITLE
Deployer un wordpress pour le site vitrine de GeomServices.

### ISSUE THREAD

**Issue by JorisPLA7** [Webanimus/geomservices#4]
### Besoin 
Le travail commercial ne devrait pas nécessiter de mettre les mains dans le code.
Si la vitrine n'a pas la même interface que le SaaS qu'il vend, pas grave pour le moment.

J'aurais besoin d'un Wordpress tout simple, pas besoin de nom de domaine pour le moment, tant que la rédaction n'est pas parfaite.

**Comment by MercierCorentin** [comment]
Là dessus jsuis chaud qu'on en parle, on est pas sûr que ce soit la meilleur idée avec @Skyedge1903 
L'avantage du thème actuel c'est qu'on peut le décliner dans toutes les technos de manière assez rapide et avec Copilot, on peut dev assez vite en html
