### ISSUE TITLE
acheter et attacher le nom de domaine geomservices.com

### ISSUE THREAD

**Issue by JorisPLA7** [Webanimus/geomservices#5]
- [x] Acheter le nom de domaine
- [x] Relier le domaine apex
- [x] Renommer les liens geomservices.webanimus.com en geomservices.com sur l'ensemble des repos
- [x] Rediriger geomservices.fr

**Comment by MercierCorentin** [comment]
![image](https://github.com/Webanimus/geomservices/assets/46066895/08b7cfdf-1f05-49f3-a512-4fd04916715c)

**Comment by MercierCorentin** [comment]
C'est bon il est revenu

**Comment by JorisPLA7** [comment]
C’était mon panier ovh mdr Le 7 août 2023 à 23:29, Corentin Mercier ***@***.***> a écrit :﻿
C'est bon il est revenu

**Comment by MercierCorentin** [comment]
En cours chez OVH 
![image](https://github.com/Webanimus/geomservices/assets/46066895/5ce95fcb-ca48-40ab-a0dd-7cbee63b9ccc)

**Comment by MercierCorentin** [comment]
Done, reste à faire:

- [ ] Mettre un CNAME pour www.geomservices.com
- [ ] Renommer les liens geomservices.webanimus.com en geomservices.com sur l'ensemble des repos
- [ ] Rajouter une redirection geomservices.webanimus.com vers geomservices.com pour éviter de casser tout lien oublié
